#pragma once

#include <cstdint>
#include <memory>
#include <vector>

namespace bbanalyzer {

//===----------------------------------------------------------------------===//
// DWARF Line Resolution for BB Cost Attribution
//===----------------------------------------------------------------------===//
//
// Problem:
// --------
// When mapping assembly instructions to IR basic blocks via DWARF debug info,
// some instructions have line 0 (unmapped) because they were generated by
// compiler phases that don't preserve debug locations:
//
//   1. Prologue/Epilogue - Frame setup/teardown from alloca/ret
//   2. Condition lowering - Helper instructions for icmp → branch
//   3. PHI elimination - Register copies inserted in predecessor blocks
//
// Solution:
// ---------
// Apply heuristics to attribute unmapped instructions to their logical BB:
//
//   Heuristic 1 (Prologue): Before first labeled instruction → Entry BB
//   Heuristic 2 (Same-BB):  Line 0 between same BB regions → that BB
//   Heuristic 3 (Cross-BB): Line 0 between different BBs → previous BB
//   Heuristic 4 (Epilogue): After last labeled instruction → Exit BB
//
// Rationale for Heuristic 3:
// --------------------------
// PHI copies are inserted in PREDECESSOR blocks by PHI elimination.
// Therefore, their cost should be attributed to the source BB, not the
// destination BB containing the PHI node. Using "previous BB" achieves this.
//
// Known Limitations:
// ------------------
// If a BB generates no labeled assembly (e.g., only zext + br that become
// no-ops), its PHI costs get attributed to the previous visible BB.
// This is acceptable as total path costs remain correct.
//
//===----------------------------------------------------------------------===//

/// Context information for resolving a line number
struct LineContext {
    unsigned prevLabeledLine;  // Previous non-zero line (0 if none)
    unsigned nextLabeledLine;  // Next non-zero line (0 if none)
    uint64_t prevLabeledAddr;  // Address of previous label (0 if none)
    uint64_t nextLabeledAddr;  // Address of next label (0 if none)
    uint64_t funcStartAddr;    // Function start address
    uint64_t funcEndAddr;      // Function end address
    unsigned entryBB;          // Entry BB index (usually 1)
    unsigned exitBB;           // Exit BB index (last BB in function)
};

/// Abstract interface for resolving DWARF line numbers.
/// Allows different resolution strategies to be implemented and tested.
class DWARFLineResolver {
public:
    virtual ~DWARFLineResolver() = default;

    /// Resolve a potentially unmapped line to a BB index.
    /// @param address      The instruction address
    /// @param rawLine      The raw DWARF line (0 = unmapped)
    /// @param context      Surrounding line context
    /// @return Resolved BB index (1-based), or 0 if truly unmapped
    virtual unsigned resolve(uint64_t address, unsigned rawLine,
                             const LineContext &context) const = 0;
};

/// Heuristic-based resolver that applies the four resolution rules.
class HeuristicLineResolver : public DWARFLineResolver {
public:
    unsigned resolve(uint64_t address, unsigned rawLine,
                     const LineContext &context) const override;
};

/// Raw line entry from DWARF parsing
struct LineEntry {
    uint64_t address;
    unsigned line;
};

/// Resolve all line 0 entries in a function's line table.
/// This is a convenience function that applies the resolver to all entries.
/// @param entries      Line entries for a single function (will be modified in place)
/// @param funcStart    Function start address
/// @param funcEnd      Function end address
/// @param resolver     The resolver to use
void resolveUnmappedLines(std::vector<LineEntry> &entries,
                          uint64_t funcStart, uint64_t funcEnd,
                          const DWARFLineResolver &resolver);

} // namespace bbanalyzer
